CONFIG_NAME: 'bird'
dataset_name: 'birds'
data_dir: 'data/birds'

imsize: 256
z_dim: 100
cond_dim: 512
manual_seed: 100
cuda: True

clip4evl: {'src':"clip", 'type':'ViT-B/32'}
clip4trn: {'src':"clip", 'type':'ViT-B/32'} 
clip4text: {'src':"clip", 'type':'ViT-B/32'} 

stamp: 'normal'
state_epoch: 0 # 0 OR 1 for resume training
max_epoch: 3 # 1502 defaults
batch_size: 32
gpu_id: 0
nf: 64
ch_size: 3

scaler_min: 64
growth_interval: 2000
lr_g: 0.0001
lr_d: 0.0004
sim_w: 4.0

gen_interval: 1 #1
test_interval: 20 #5
save_interval: 1 #20

sample_times: 12
npz_path: 'data/birds/npz/bird_val256_FIDK0.npz'
log_dir: 'new'

multi_gpus: False
model: GALIP
num_workers: 8 # 4 OR 8
local_rank: -1
mixed_precision: False
pretrained_model_path: code/saved_models/data/model_save_file